// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fqstbeaarygxbrlpfuck.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZxc3RiZWFhcnlneGJybHBmdWNrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY1Njg4NjksImV4cCI6MjA3MjE0NDg2OX0.LFH-C1G5fOdmfFkKCNbqh2YIjqXIu1XTsEYQulZmQ00";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});